5. Предположим, мы взвешиваем  груши (х),  яблоки (y) и сливы (z).  
При этом, у нас есть дополнительная априорная информация о предполагаемом весе фруктов:  
предварительная оценка веса груши ~150, яблока у~100,  а сливы z~50?.  Оцените вес яблок, груш и слив:  
**х+2у+5z=550**  
**3х+у+3z=800**  


In [1]:
import numpy as np
import scipy.linalg

In [2]:
A = np.array([[1,2,5],[3,1,3]])
B = np.array([550, 800])
X_0 = np.array([150, 100, 50])
print("A:", A, sep="\n")
print("B:", B, sep="\n")
print("X_0:", X_0, sep="\n")

A:
[[1 2 5]
 [3 1 3]]
B:
[550 800]
X_0:
[150 100  50]


In [3]:
B_0 = np.dot(A, X_0)
print("B_0:", B_0, sep="\n")

B_0:
[600 700]


In [4]:
diff_B = B - B_0
print("diff_B:", diff_B, sep="\n")

diff_B:
[-50 100]


In [5]:
diff_B_lstsq_solver = np.linalg.lstsq(A, diff_B, rcond=None)
diff_B_lstsq_solver

(array([ 53.23529412, -11.17647059, -16.17647059]),
 array([], dtype=float64),
 2,
 array([6.72625219, 1.93843532]))

In [6]:
X_s_volnoy = diff_B_lstsq_solver[0]
print("X_s_volnoy:", X_s_volnoy, sep="\n")

X_s_volnoy:
[ 53.23529412 -11.17647059 -16.17647059]


**X_s_volnoy = X - X_0**

In [7]:
X = X_s_volnoy + X_0
print("X:", X, sep="\n")

X:
[203.23529412  88.82352941  33.82352941]


**Решение Анны:**

In [8]:
x0 = np.array([150, 100, 50])  

a = np.array([[1, 2, 5], [3, 1, 3]])  
b = np.array([550, 800])  
  
x = np.linalg.lstsq(a, b, rcond=None)  
print(x[0])  
  
b0 = np.dot(a, x0)  
print(b0)  
  
db = b - b0  
print(db)  
  
dx = np.linalg.lstsq(a, db, rcond=None)  
print(dx[0])  
  
X = x[0] - dx[0]  
print(X)

#А надо вот так:
X = x0 + dx[0]  
print(X)

[196.76470588  11.17647059  66.17647059]
[600 700]
[-50 100]
[ 53.23529412 -11.17647059 -16.17647059]
[143.52941176  22.35294118  82.35294118]
[203.23529412  88.82352941  33.82352941]
